config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'

  resources :users, only: [:edit, :update]

  scope module: 'user' do
    resources :images, only: :show
  end

  resources :channels, only: :show

  root to: 'channels#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages, dependent: :delete_all

  scope :with_message_count, -> { left_outer_joins(:messages).select("channels.*, COUNT(messages.id) AS message_count").group(:id) }
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable, :registerable

  validates :username, uniqueness: true, presence: true

  has_many :messages, dependent: :delete_all
  has_one_attached :image

  after_create :add_default_image

  def email_required?
    false
  end

  def will_save_change_to_email?
    false
  end

  private

  def add_default_image
    return if image.attached?
    image_path = Rails.root.join(
      'app', 'assets', 'images', 'placeholder-icon.png'
    )
    default_image = File.open(image_path)
    self.image.attach(
      io: default_image,
      filename: 'default-image.png',
      content_type: 'image/png'
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_channels

  def set_channels
    @channels = Channel.with_message_count.order(:name)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %w[image])
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel

  def show
    @messages = @channel.messages.includes(:user, :channel)
      .order(:created_at).as_json(include: [:user])
  end

  private

  def set_channel
    @channel = Channel.find_by(id: params[:id]) || Channel.first
  end
end

app/controllers/user/images_controller.rb
class User::ImagesController < ApplicationController
  def show
    user = User.find_by(id: params[:id])
    redirect_to rails_blob_url(user.image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def edit
  end

  def update
  end

  private

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/show.slim
= react_component 'ChannelDisplay', messages: @messages, channel: @channel, user: current_user

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | ChatCable
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .row.chat-container
      .col-md-2.sidebar
        .channels
          = render partial: 'shared/sidebar'
        .sign-out
          = link_to 'Sign Out', destroy_user_session_path, class: 'justify-content-center d-flex', method: :delete
      .chatbox.col-md-10
        = yield

app/views/layouts/application.slim
doctype html
html
  head
    title
      | ChatCable
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .row.chat-container
      .col-md-2.sidebar
        .channels
          = render partial: 'shared/sidebar'
        .sign-out
          = link_to 'Sign Out', destroy_user_session_path, class: 'justify-content-center d-flex', method: :delete
      .chatbox.col-md-10
        = yield

app/views/layouts/devise.slim
doctype html
html
  head
    title
      | ChatCable
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/shared/_sidebar.slim
.sidebar-contents.col-md-12
  .sidebar-header
    h4 Chat Cable
    = link_to edit_user_path(current_user), class: 'edit-profile-link', remote: true
      .small Edit Profile
  hr
  ul.list-group.list-unstyled
    li
      = link_to '#channels-submenu', class: 'dropdown-toggle list-group-item', data: { toggle: 'collapse' }
        = 'Channels'

      ul#channels-submenu.collapse.list-unstyled.show.list-group.sub-menu
        - @channels.each_with_index do |channel, index|
          li
            = link_to channel_path(channel.id), class: "d-flex justify-content-between align-items-center list-group-item highlightable #{channel.id == params[:id].to_i || (params[:id].to_i == 0 && index == 0) ? 'active' : ''}"
              = channel.name
              span class="badge badge-primary badge-pill #{channel.message_count.zero? ? 'd-none' : ''}" = channel.message_count

#profile-modal.modal.fade.show
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title HEY DUDE
      .modal-body
        span DON'T MAKE ME CRY~

app/views/users/_profile.slim
#profile-modal.modal.fade.show
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title HEY DUDE
      .modal-body
        span DON'T MAKE ME CRY~

app/views/users/edit.js.erb
$('.chat-container').append("<%= j render 'profile', locals: { user: @user } %>")
$('#profile-modal').modal()